### PR TITLE
update stopword.php

### PR DESCRIPTION
**Pull request by hafriz**
Warning: include(../stemmer/stemmer.php): failed to open stream: No such file or directory

### CODE REVIEW

**Comment by thoriqadillah** [comment]
Is the original `include('./../stemmer.php');` in stemmer/en/en.php and `include('../stemmer/stemmer.php');` in stopword/stopword.php throwing error?
Is the `include('./../stemmer.php');` in stemmer/id/id.php throwing error too?

**Comment by hafriz** [comment]
Yes, it throwing error, and i found en.php also throwing error.

What moodle version this plugin compatible with? I'm testing it on moodle
4.1

**Comment by thoriqadillah** [comment]
4.1 should be fine. This plugin developed on v4.0
It's pretty weird because i have no problem with the include. I even try it without using include whatsoever and the stopword and stemmer is still working.
What OS are you using? I'm using linux

Can you try on your machine to change the include both on stopword and stemmer with the following code?
```php
global $CFG;
require_once($CFG->dirroot.'/question/type/essaysimilarity/nlp/preprocessing/stemmer/stemmer.php');
``` 

If that's working, I might change the `include` to `require_once` with absolute path instead of relative path

**Comment by hafriz** [comment]
I made the change to the code, and there are no longer any warning errors.
I try to preview the question this warning error came out

Warning: Undefined array key "format" in
/question/type/essaysimilarity/question.php on line 136

**Comment by thoriqadillah** [comment]
Can you give me the steps to reproduce the error?

**Comment by hafriz** [comment]
hi, I have updated the code with the correct variable, in question.php it
should use answerformat

also in renderer.php line 186, there is another missing variable $plagiarism

Now all the warnings and the plugin seem to be working accordingly. I will
do some more tests on the plugins.

the step to reproduce the error :

You just need to create the question, preview it and then try to submit the
answer. once submit the warning error will show. (need to enable moodle
debug mode)

**Comment by thoriqadillah** [comment]
Woops, a typo for sure. I thought it was `$response['format']` instead of `$response['answerformat']`. Yep, thanks. Don't forget to remove the comment from the code
Can you update the include in the stemmer for `id.php` like before as well, please? I will test it later. Thanks

**Review by thoriqadillah — APPROVED** [review]
LGTM

**Pull request merged**
